config/routes.rb
Rails.application.routes.draw do
  resources :gossips do
    resources :comments
    resources :likes
  end

  resources :cities, only: [:index, :show]
  resources :tag, only: [:index]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'welcome/:first_name', to: 'welcome#first_name'
  get '/static_pages/contact', to: 'static_pages#contact'
  get '/static_pages/team', to: 'static_pages#team'
  get '/static_pages/home', to: 'static_pages#home'
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user

  has_many :linktags
  has_many :tags, through: :linktags

  has_many :likes

  has_many :comments

  validates :title, length: { in: 3..13 }
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/linktag.rb
class Linktag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :linktags
    has_many :gossips, through: :linktags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city

  has_many :gossips

  has_many :likes, dependent: :destroy

  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  has_many :comments

  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password

  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+.)+[^@\s]+\z/, message: "email adress please" }
  validates :first_name , presence: true
  validates :last_name, presence: true
  validates :city, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 before_action :find_gossip!
 before_action :authenticate_user, only: [:new, :create]

  def new
    @comment = Comment.new
  end

  def create
    @comment = @gossip.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to gossip_path(find_gossip!)
     flash[:notice] = 'Ton commentaire est en ligne'
    else
      render gossip_path(find_gossip!)
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    post_params = params.require(:comment).permit(:content)
    if @comment.update(post_params)
      redirect_to gossip_path(find_gossip!)
      flash[:notice] = 'Ton commentaire a bien étais modifié'
    else
      render 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to gossip_path(find_gossip!)
  end

  private

  def find_gossip!
    @gossip = Gossip.find(params[:gossip_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def authenticate_user
    unless current_user
      flash[:danger] = "Connecte-toi"
      redirect_to new_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_team_helper.rb
module StaticTeamHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/edit.html.erb
<html>
  <body>

    <div class="jumbotron jumbotron-fluid" id="jumbotron-edit">
      <div class="container-fluid blockquote text-center">
        <% if @gossip.errors.any? %>
          <div class="alert alert-warning text-center" role="alert">
            <p>Nous n'avons pas réussi à modifier ton commentaire pour les raisons suivante :</p>
            <ul>
              <% @gossip.errors.full_messages.each do |message| %>
                <%= message %><br />
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="container d-flex justify-content-around text-center">
        <h2 class="list-group-item active" style="width: 25rem;">Edite ton commentaire :</h2>
        </div>
        
        <div class="container text-white" id="transparent"  style="max-width: 25rem;">
          <div class="container d-flex justify-content-center text-center" style="max-width: 30rem" id="transparent-form">
            <%= form_for([@gossip, @comment]) do |f| %>
            
            <label class="mt-3">Contenu :</label><br />
            <%= f.text_area :content %>
            <br /> <br />
            <button type="submit" class="btn btn-primary mb-3">Editer</button>
            <a class="btn btn-warning mb-3" href="<%=gossip_comment_path(@gossip, @comment)%>" data-confirm="êtes vous sur de vouloir supprimer ce gossip ?" data-method="DELETE">Supprimer</a>
      
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>