config/routes.rb
Rails.application.routes.draw do
  resources :gossips do
    resources :comments
    resources :likes
  end

  resources :cities, only: [:index, :show]
  resources :tag, only: [:index]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'welcome/:first_name', to: 'welcome#first_name'
  get '/static_pages/contact', to: 'static_pages#contact'
  get '/static_pages/team', to: 'static_pages#team'
  get '/static_pages/home', to: 'static_pages#home'
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user

  has_many :linktags
  has_many :tags, through: :linktags

  has_many :likes

  has_many :comments

  validates :title, length: { in: 3..13 }
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/linktag.rb
class Linktag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :linktags
    has_many :gossips, through: :linktags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city

  has_many :gossips

  has_many :likes, dependent: :destroy

  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  has_many :comments

  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password

  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+.)+[^@\s]+\z/, message: "email adress please" }
  validates :first_name , presence: true
  validates :last_name, presence: true
  validates :city, presence: true
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:show, :new, :create]
  before_action :is_author?, only: [:edit, :update, :destroy]

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @tag = Tag.all
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user: current_user)
    if @gossip.save
      params[:tag].try(:each) do |i|
        @linktag = Linktag.new(tag_id: Tag.find(i).id, gossip_id: @gossip.id)
        @linktag.save
      end
      redirect_to @gossip
      flash[:notice] = 'Ton gossip a bien était enregistré'
    else
      render 'new'
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    post_params = params.require(:gossip).permit(:title, :content)
    if @gossip.update(post_params)
      redirect_to @gossip
      flash[:notice] = 'Ton gossip a bien était modifié'
    else
      render 'edit'
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to "/"
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Connecte-toi"
      redirect_to new_session_path
    end
  end

  def is_author?
    @gossip = Gossip.find(params[:id])
    unless current_user == @gossip.user
      flash[:danger] = "action impossible, tu n'es pas l'auteur"
      redirect_to @gossip
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_team_helper.rb
module StaticTeamHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/edit.html.erb
<html>
  <body>

    <div class="jumbotron jumbotron-fluid" id="jumbotron-edit">
      <div class="container-fluid blockquote text-center">
        <% if @gossip.errors.any? %>
          <div class="alert alert-warning text-center" role="alert">
            <p>Nous n'avons pas réussi à modifier le potin pour la (ou les) raison(s) suivante(s) :</p>
            <ul>
              <% @gossip.errors.full_messages.each do |message| %>
                <%= message %><br />
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="container d-flex justify-content-around text-center">
        <h2 class="list-group-item active" style="width: 25rem;">Edite ton gossip :</h2>
        </div>
        
        <div class="container text-white" id="transparent"  style="max-width: 25rem;">
          <div class="container d-flex justify-content-center text-center" style="max-width: 30rem" id="transparent-form">
            <%= form_for @gossip do |f| %>
            
            <label class="mt-3">Titre</label><br />
            <%= f.text_field :title %>
            <br /> <br />
      
            <label>Contenu</label><br />
            <%= f.text_area :content%>
            <br /> <br />
      
            <button type="submit" class="btn btn-primary mb-3">Editer</button>
      
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/gossips/new.html.erb
<html>
  <body>

    <div class="jumbotron jumbotron-fluid" id="jumbotron-form">
      <div class="container-fluid blockquote text-center">
      <% if @gossip.errors.any? %>
          <div class="alert alert-warning text-center" role="alert">
            <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
            <ul>
              <% @gossip.errors.full_messages.each do |message| %>
                <%= message %><br />
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="container d-flex justify-content-around text-center">
        <h2 class="list-group-item active" style="width: 25rem;">Ecris ton gossip :</h2>
        </div>
        <div class="container d-flex flex-column text-white" id="transparent"  style="max-width: 25rem; max-height: 50rem">
          <div class="container d-flex justify-content-around text-center" style="max-width: 30rem" id="transparent-form">
            <%= form_tag url_for(action: 'create'), class: "my-4", method: "post" do %>
            
            <%= label_tag 'Titre' %><br />
            <%= text_field_tag :title %>
            <br /> <br />
      
            <%= label_tag 'Contenu' %><br />
            <%= text_area_tag :content %>
            <br /> <br />

            <%= label_tag 'Tags :' %><br />
            <%= select_tag 'tag', options_for_select(Tag.all.collect{ |u| [u.title, u.id] }), multiple: true, :class => "form-control mb-3" %>
            <br />
      
            <%= submit_tag "Créer le gossip", class: "btn btn-primary" %>
      
            <% end %>
          </div>
        </div>
      </div>
    </div>
    
  </body>
</html>

app/views/gossips/show.html.erb
<body>
  <div class="jumbotron jumbotron-fluid" id="jumbotron-gossip">
    <div class="container-fluid blockquote text-center">
      <div class="container text-white" id="transparent"  style="max-width: 20rem;">
        <div class="container">
          <div class="card-body">
            <h5 class="card-title"><%= @gossip.title %></br></h5>
            <p class="card-text"><%= @gossip.content %></p>
            <p class="blockquote-footer text-light"> Tags :
            <% @gossip.tags.each do |x| %>
            <%= x.title %>   
            <% end %>
            </p>


            </p>
            <p class="blockquote-footer text-light">Auteur : <a class="" href="<%=user_path(@gossip.user)%>"><%=@gossip.user.first_name%></p></a>
            <p class="blockquote-footer text-light">Ville de l'auteur : <br /> <a class="" href="<%= city_path(@gossip.user.city)%>"><%=@gossip.user.city.name%></p></a>
            <p class="blockquote-footer"> Commentaires : <%= @gossip.comments.count %></p>
            <p><%= @gossip.likes.count %> <%= (@gossip.likes.count) <= 1 ? 'Like' : 'Likes'%></p>
            <% pre_like = @gossip.likes.find { |like| like.user_id == current_user.id} %>
            <% if pre_like %>
              <a class="btn btn-outline-primary"  <%= link_to 'Unlike', gossip_like_path(@gossip, pre_like), method: :delete %></a>
            <% else %>
              <a class="btn btn-outline-primary"  <%= link_to 'Like', gossip_likes_path(@gossip), method: :post  %></a>
            <% end %>
            <% if current_user == @gossip.user %>
            <div class="btn-group" role="group" aria-label="Basic example">
              <a class="btn btn-primary" <%= link_to "Editer", edit_gossip_path(@gossip)%></a>
              <a class="btn btn-warning" href="<%=gossip_path(@gossip)%>" data-confirm="êtes vous sur de vouloir supprimer ce gossip ?" data-method="DELETE">Supprimer</a>
            </div>
            <% end %>
          </div>
          <div class="text-muted">
            <%= @gossip.created_at %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% flash.each do |type, msg| %>
    <div class="d-flex justify-content-center mt-2">
      <div class="alert alert-info" style="max-width: 50rem">
        <%= msg %>
      </div>
    </div>
  <% end %>
  
  <div class="container">
  <h2 class="text-center text-light mb-4">Commentaires :</h2>
 
    <% @gossip.comments.each_with_index do |comment, index| %>
      <div class="card text-white bg-dark m-2" >
        <div class="card-body">
        <h5 class="card-title"> <a class="text-primary" href="<%=user_path(comment.user)%>"><%= comment.user.first_name %> :</a></h5>
          <p class="card-text"><%= comment.content %></p>
          <% if current_user == comment.user %>
          <a class="btn btn-primary" <%= link_to "Editer", edit_gossip_comment_path(@gossip, comment)%></a>
          <% end %>
        </div>
      </div>
    <% end %>

</div>
<div class="d-flex justify-content-center my-4">
    <%= form_for([@gossip, @gossip.comments.build]) do |f| %>
      <%= f.text_area :content, class: "rounded", style: "width: 40rem; height: 2rem", placeholder: "Ecris-ton commentaire" %>
      <%= f.submit "Créer", class: 'mx-2 btn btn-primary position-absolute', style: "height: 2rem; padding: 1px"%>
  <% end %>
</div>
</body>